### ISSUE TITLE
About occlusion map

### ISSUE THREAD

**Issue by 36572545** [HyeongminLEE/AdaCoF-pytorch#1]
Hi~! In your paper, the element of occlusion map is either 0 (implies the pixel is visible only in I_(n+1)) or 1(implies the pixel is visible only in I_n). How do you know which pixels are visible in both input frames, as your paper section "offset visualization" shows?

**Comment by HyeongminLEE** [comment]
The occlusion map can be not only 0 or 1, but also any real number between 0 and 1. When the pixels are visible in both input frames, the occlusion map value becomes 0.5.

Thank you!!

**Comment by 36572545** [comment]
Oh, my fault. Thanks a lot!
