### ISSUE TITLE
gradient to input

### ISSUE THREAD

**Issue by laomao0** [HyeongminLEE/AdaCoF-pytorch#10]
https://github.com/HyeongminLEE/AdaCoF-pytorch/blob/master/cupy_module/adacof.py

In this file, why the gradient to input equals to zero directlly?

**Comment by HyeongminLEE** [comment]
In my code, there's no need for input's gradient, because all inputs are input images (data). So I did not implement the gradient for input. Thanks!

**Comment by laomao0** [comment]
> In my code, there's no need for input's gradient, because all inputs are input images (data). So I did not implement the gradient for input. Thanks!

Thanks for your reply.
