### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/vimeo_triplet/Beanbags/frame10.png'

### ISSUE THREAD

**Issue by luanyue-ly** [HyeongminLEE/AdaCoF-pytorch#11]
(AdaCof) root@e82d0083b966:/mnt/AdaCoF# python train.py --train /mnt/vimeo_triplet --out_dir /mnt/AdaCoF/output
1.000 * Charb
0.010 * g_Spatial
0.005 * g_Occlusion
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    main()
  File "train.py", line 65, in main
    my_trainer = Trainer(args, train_loader, TestDB, model, loss, start_epoch)
NameError: name 'TestDB' is not defined
(AdaCof) root@e82d0083b966:/mnt/AdaCoF# python train.py --train /mnt/vimeo_triplet --out_dir /mnt/AdaCoF/output
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    main()
  File "train.py", line 54, in main
    TestDB = Middlebury_other(args.test_input, args.gt)
  File "/mnt/AdaCoF/TestModule.py", line 39, in __init__
    self.input0_list.append(to_variable(self.transform(Image.open(input_dir + '/' + item + '/frame10.png')).unsqueeze(0)))
  File "/opt/conda/envs/AdaCof/lib/python3.7/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/vimeo_triplet/Beanbags/frame10.png'

**Comment by HyeongminLEE** [comment]
How did you set the argument '--test_input' ?

**Comment by luanyue-ly** [comment]
I've solved it. Thank you @HyeongminLEE

**Comment by HyeongminLEE** [comment]
Thanks!
