### ISSUE TITLE
only interpolate one frame?

### ISSUE THREAD

**Issue by EAGLE50** [HyeongminLEE/AdaCoF-pytorch#3]
in interpolate_video.py , is  the arg of '--dilation' useless? I want to inpterpolate 4 frame , such as from 30fps to 120fps. Could you tell me  what should I do. thanks

**Comment by HyeongminLEE** [comment]
The arguments such as dilation and kernel size can be taken from config.txt file. However, when the config file does not contain dilation or kernel size, the arguments become meaningful.

If you want to interpolate 4 frames, you can run interpolate_video.py twice.

Thanks.

**Comment by EAGLE50** [comment]
OK. I got it. thanks
