### ISSUE TITLE
Map Visualisation

### ISSUE THREAD

**Issue by issakh** [HyeongminLEE/AdaCoF-pytorch#4]
Hi, in your paper you show the occlusion, meanflow and varflow maps. How can I output these maps?
Thanks

**Comment by HyeongminLEE** [comment]
The shared version does not contain the visualization code.
I recommend you modify the code to output the parameters (weight, offset, occlusion map).
For the figures on the paper, we saved the weight, offset, and occlusion maps into mat files.
Then we visualized them using MATLAB.

Thanks

**Comment by issakh** [comment]
Hi, thanks for your response, I have returned the occlusion parameter as a test and used torch.save(Occlusion , 'map.mat'), tried to open that in MATLAB, but got an error. Is there something I'm missing here?
Thanks again

**Comment by issakh** [comment]
Hi, thanks for your response, I saved the occlusion parameter as a test and used torch.save(Occlusion , 'map.mat'), I tried to open that in MATLAB, but got an error. Is there something I'm missing here?
Thanks again

**Comment by HyeongminLEE** [comment]
Try converting the tensor to numpy array and "scipy.io.savemat".

**Comment by issakh** [comment]
So what I've done is this in the adacofnet.py file:
```
        Occlusion2 = Occlusion.clone().detach().cpu().numpy()
        savemat('occlusion.mat',dict(Occlusion2))
```
However I get valueerror:
 dictionary update sequence element #0 has length 1; 2 is required

Doing  savemat('occlusion.mat',Occlusion2) gets me this error:
AttributeError: 'numpy.ndarray' object has no attribute 'values'

Do you have any ideas?

**Comment by HyeongminLEE** [comment]
The shape of tensor in 4 rank. So you have to squeeze tensor. (Remove batch axis)
We use
`savemat('out.mat', {'Occlusion': Occlusion.squeeze().cpu().detach().numpy()})`

**Comment by issakh** [comment]
Thanks for this, the file saves fine and loads in matlab. I am now trying the plot this file, I have got something similar but it's in greyscale, how would I get the colour image you got?
![untitled](https://user-images.githubusercontent.com/58527901/87039406-04c75580-c1e7-11ea-8ab9-9d5d70a7ac83.png)

**Comment by HyeongminLEE** [comment]
That could be done in MATLAB.
You just have to make the grayscale image into color(hue) image.
First, normalize the map to be 0~0.5(multiply 0.5). This is because the color code is red to red, so the minimum(0) and maximum(1) value may not distinctive.
Then, set the map you got as the first channel of image and fill the second and third channels with 1.
Finally, convert the image with hsv2rgb.

Thanks.

**Comment by issakh** [comment]
Thanks, I have tested this out and looks fine. For the mean flow and variance maps, how would they be implemented, would you do something like torch.mean((Weight1*Alpha1)-(Weight1*Beta1))?

**Comment by HyeongminLEE** [comment]
Just as the definition of variance. sum(w*(x-mean)^2)

**Comment by issakh** [comment]
Hi sorry to reopen this thread after such a long time, but I'm still facing problems regarding the implementation of the mean flow map and variance map
So what I have done for mean flow map is:
or mean1 = torch.mean((Weight1*Alpha1))+(Weight1*Beta1)
mean2 =  torch.mean((Weight2*Beta2))+(Weight2*Alpha2)
I'm not sure how to do the variance
torch.sum(weight1*(fm-mean) + weight2*(fm-mean))
I'm not sure how to get fm though.
Can you please clarify how to compute mean and variance flow in torch as I am a bit lost
Thanks

**Comment by HyeongminLEE** [comment]
Because Alpha and Beta are the parameters for x-axis and y-axis, you have
to calculate the mean flow as following:

mean1 = [torch.sum(Weight1*Alpha1*), torch.sum(Weight1*Beta1*)]
mean2 = [torch.sum(Weight2*Alpha2*), torch.sum(Weight2*Beta2*)]

then the calculated mean1 and mean2 are fm.
So you can calculate variance map as follows

var1 = l2norm[torch.sum( Weight1 ( Alpha1 - mean1(x-axis))^2), torch.sum(
Weight1 (Beta1 - mean1(y-axis ))^2) ]
var2 = l2norm[torch.sum( Weight2 ( Alpha2 - mean2(x-axis))^2), torch.sum(
Weight2 (Beta2 - mean2(y-axis ))^2) ]

for more detail, please refer to the equations (13)(14)(15) from the paper.

Thanks

*---------------------------------------------------------------------------------------------*
Hyeongmin Lee
Undergraduate Student

Image and Video Pattern Recognition Lab.
Department of Electrical and Electronic Engineering
Yonsei Univ. Rep. of Korea
Web: https://hyeongminlee.github.io/

*---------------------------------------------------------------------------------------------*


2021년 3월 2일 (화) 오전 3:19, issakh <notifications@github.com>님이 작성:

**Comment by issakh** [comment]
Thanks for your quick response! 
I have done this (got an error with the ones for the mean):
mean1 = [torch.sum(Weight1 * Alpha1 ), torch.sum(Weight1 * Beta1 )]
mean2 =[torch.sum(Weight2 * Alpha2 ), torch.sum(Weight2 * Beta2 )]
But I get a list which I'm not sure how to visualise
I then tried:
mean1 = torch.dist(torch.sum(Weight1 * Alpha1 ), torch.sum(Weight1 * Beta1 ),2)
mean2 = torch.dist(torch.sum(Weight2 * Alpha2 ), torch.sum(Weight2 * Beta2 ),2)
But as I get whole values here e.g. for mean2 107865.3281 (on beanbags image), how would you get the flow map. As a result, the method of using the savemat function (like what was used with the occlusion) doesn't work here. So how do you visualise the mean flow (and variance) maps as in figure 6 in your paper?

**Comment by HyeongminLEE** [comment]
Hi issakh,

I send you the matlab source code for the motion parameter visualization.
Please compare your code with it and reply whenever you have additional
questions.

Thanks,
Hyeongmin

*---------------------------------------------------------------------------------------------*
Hyeongmin Lee
Undergraduate Student

Image and Video Pattern Recognition Lab.
Department of Electrical and Electronic Engineering
Yonsei Univ. Rep. of Korea
Web: https://hyeongminlee.github.io/

*---------------------------------------------------------------------------------------------*


2021년 3월 2일 (화) 오후 9:41, issakh <notifications@github.com>님이 작성:

**Comment by issakh** [comment]
Hi, thanks for your help, it doesn't show that there is anything attached. Sometimes when you reply from email the attachments don't show. Can you please attach it again?
Thanks again

**Comment by HyeongminLEE** [comment]
I share it with google drive

https://drive.google.com/file/d/1-wsdvlOhR178g2G1oYWuWFECUaY2cMtM/view?usp=sharing

please do not share this link with others, and just use this code to
compare and improve your code.

Thanks

*---------------------------------------------------------------------------------------------*
Hyeongmin Lee
Undergraduate Student

Image and Video Pattern Recognition Lab.
Department of Electrical and Electronic Engineering
Yonsei Univ. Rep. of Korea
Web: https://hyeongminlee.github.io/

*---------------------------------------------------------------------------------------------*


2021년 3월 3일 (수) 오후 8:02, issakh <notifications@github.com>님이 작성:

**Comment by issakh** [comment]
Great thank you! I will take a look at it and see how to use it. If you want you can remove the google drive link now as have downloaded it :)
I would really like to thank you again for your help

**Comment by issakh** [comment]
Or you could delete the post, as your post is visible on github issue section

**Comment by HyeongminLEE** [comment]
Thanks! I removed the link.

**Comment by issakh** [comment]
Hi, when doing the Middlebury benchmark, what function did you use for measuring runtime on Urban sequence? Is there a method in torch to do this?

**Comment by HyeongminLEE** [comment]
I just used Python time library.
