### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Heroandzhang** [HyeongminLEE/AdaCoF-pytorch#7]
Hello,I see sentences about datasets in your paper.
These sentences are'Training Dataset. We use Vimeo90K dataset for training. It contains 51,312 triplets of 256 × 448 video frames.'
But when i training with the ‘vimeo_triplet’ folder ,i find it contains 73191 triplets.
I want to ask you, if the number of training datasets is different from you, what are the adverse effects？
thank you!

**Comment by HyeongminLEE** [comment]
There might be a slight difference in PSNR, but probably the gap will be usually not significant.
The changes when training AdaCoF on various datasets show the same tendency as when training other general networks.
